info:
  contact: {}
  description: This is a sample server celler server.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /signup:
    post:
      consumes:
      - application/json
      description: Register a new user
      parameters:
      - description: Email
        in: body
        name: email
        required: true
        schema:
          type: string
      - description: Password
        in: body
        name: password
        required: true
        schema:
          type: string
      - description: Tenant ID
        in: body
        name: tenant_id
        required: true
        schema:
          type: integer
      - description: Is Active
        in: body
        name: is_active
        schema:
          type: boolean
      - description: Profile Type
        in: body
        name: profile_type
        schema:
          type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Signup realizado com sucesso!
          schema:
            type: string
      tags:
      - users
swagger: "2.0"
